---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)

#need to put the dashboard.Rmd on the desktop instead of inside the project
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% #orginally 5stars with half stars, changing into a 10 stars scale
  select(neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan", 
    room_type == "Entire home/apt", 
    price %in% 100:500
  ) %>% 
  drop_na(stars)
```
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price, "\nStars: ", stars)  #\n starting a new line
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers", 
    color = ~price, alpha = .5, text = ~text_label
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) %>% 
  plot_ly(
    y = ~price, color = ~neighbourhood, type = "box", 
    colors = "viridis")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", 
    colors = "viridis")
```

